name: datatransport

on:
  pull_request:
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

jobs:
  pod_lib_lint:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [ios, tvos, macos, watchos]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Scripts Directory
      run: ./setup-scripts.sh
    - name: Setup Bundler
      run: ./scripts/setup_bundler.sh
    - name: PodLibLint DataTransport
      run: |
        scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb GoogleDataTransport.podspec --platforms=${{ matrix.target }}

  catalyst:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Scripts Directory
      run: ./setup-scripts.sh
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Setup project and Test Catalyst
      run: scripts/third_party/travis/retry.sh scripts/test_catalyst.sh GoogleDataTransport build

  watchos-testapp:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
    - name: Setup Scripts Directory
      run: ./setup-scripts.sh
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Prereqs
      run: scripts/install_prereqs.sh GoogleDataTransport watchOS xcodebuild
    - name: Setup project and build watchOS test app
      run: scripts/third_party/travis/retry.sh scripts/build.sh GoogleDataTransport watchOS xcodebuild

  datatransport-options-matrix:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [ios, tvos, macos, watchos]
        flags: [
          '--use-static-frameworks',
          '--use-libraries'
        ]
    needs: pod_lib_lint
    steps:
    - uses: actions/checkout@v2
    - name: Setup Scripts Directory
      run: ./setup-scripts.sh
    - name: Setup Bundler
      run: ./scripts/setup_bundler.sh
    - name: PodLibLint DataTransport Cron
      run: |
        scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb GoogleDataTransport.podspec --platforms=${{ matrix.target }} ${{ matrix.flags }}
