name: test_coverage

on:
  pull_request:
    # open will be triggered when a pull request is created.
    # synchronize will be triggered when a pull request has new commits.
    # closed will be triggered when a pull request is closed.
    types: [opened, synchronize, closed]

jobs:
  pod-lib-lint-googledatatransport:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'firebase/firebase-ios-sdk'
